{"time":"2025-01-21T14:22:17.1155583+02:00","level":"INFO","msg":"using version","core version":"0.19.0"}
{"time":"2025-01-21T14:22:17.1160749+02:00","level":"INFO","msg":"created symlink","path":"C:\\Users\\User\\Documents\\herbskeeper\\HerbKeeper\\wandb\\run-20250121_142217-Herb_Keeper 9\\logs\\debug-core.log"}
{"time":"2025-01-21T14:22:17.2294075+02:00","level":"INFO","msg":"created new stream","id":"Herb_Keeper 9"}
{"time":"2025-01-21T14:22:17.2294075+02:00","level":"INFO","msg":"stream: started","id":"Herb_Keeper 9"}
{"time":"2025-01-21T14:22:17.2294075+02:00","level":"INFO","msg":"sender: started","stream_id":"Herb_Keeper 9"}
{"time":"2025-01-21T14:22:17.2294075+02:00","level":"INFO","msg":"handler: started","stream_id":"Herb_Keeper 9"}
{"time":"2025-01-21T14:22:17.2294075+02:00","level":"INFO","msg":"writer: Do: started","stream_id":"Herb_Keeper 9"}
{"time":"2025-01-21T14:22:17.6146984+02:00","level":"INFO","msg":"Starting system monitor"}
{"time":"2025-01-21T14:30:32.2919946+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 192.168.205.6:55696->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
